version: '2'
services:
  mariadb:
    image: mariadb:5.5
    container_name: mariadb
    networks:
    - tlog
    volumes:
    - "./database:/var/lib/mysql"
    ports:
    - "9001:3306"
    environment:
    - MYSQL_DATABASE=timelogger
    - MYSQL_USER=root
    - MYSQL_PASSWORD=katika
    - MYSQL_ROOT_PASSWORD=katika
networks:
  tlog:
    driver: bridge
